#!/usr/bin/env php
<?php
namespace TranslationsFinder;
define( 'VENDOR_PATH', __DIR__ . '/../../vendor/' ); 

require VENDOR_PATH . 'autoload.php';
require __DIR__ . '/Find.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Find);
$application->run();
